//mutations
export const SET_CONNECTION_ID = 'SET_CONNECTION_ID'
export const GET_ALL = 'GET_ALL'
export const SET_SELECTED_ACCESSION = 'SET_SELECTED_ACCESSION'
export const UPDATE_TEXT_SEARCH = 'UPDATE_TEXT_SEARCH'
export const UPDATE_ACCESSION = 'UPDATE_ACCESSION'
export const SET_FILTERS_WORKLIST = 'SET_FILTERS_WORKLIST'
export const SET_FILTER_DATES = 'SET_FILTER_DATES'
export const LOCK_ACCESSION = 'LOCK_ACCESSION'
export const UNLOCK_ACCESSION = 'UNLOCK_ACCESSION'
export const UPDATE_ACCESSION_LOCKING = 'UPDATE_ACCESSION_LOCKING'
export const SYNC_UPDATE_ACCESSION_FROM_SERVER = 'SYNC_UPDATE_ACCESSION_FROM_SERVER'

//WIZARD
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP'
// 
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

//global
export const LOADED_SUCCESS = 'LOADED_SUCCESS'
export const LOADING_START = 'LOADING_START'
export const CHAGE_LOADING_MESAGE = 'CHAGE_LOADING_MESAGE'
export const NOTIFY_ERRORS = 'NOTIFY_ERRORS'
export const RESET_STATE = 'RESET_STATE'
