export const GET_ALL = 'GET_ALL'
export const SET_FILTERS_WORKLIST = 'SET_FILTERS_WORKLIST'
export const UPDATE_ACCESSION_WORKLIST = 'UPDATE_ACCESSION_WORKLIST'
export const UPDATE_WORKLIST_DATA = 'UPDATE_WORKLIST_DATA'
