export const GET_ALL = 'GET_ALL'
export const SET_SELECTED_ACCESSION = 'SET_SELECTED_ACCESSION'
export const UPDATE_TEXT_SEARCH = 'UPDATE_TEXT_SEARCH'
export const UPDATE_ACCESSION = 'UPDATE_ACCESSION'
